package org.example;
// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.util.concurrent.TimeUnit;



public class CreateProjectTest {
  private WebDriver driver;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    System.setProperty("webdriver.gecko.driver", "geckodriver.exe");
    driver = new FirefoxDriver();
    driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
    js = (JavascriptExecutor) driver;
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void createProject() {
    driver.get("https://crm.geekbrains.space/user/login");
    driver.manage().window().setSize(new Dimension(1550, 838));
    driver.findElement(By.name("_username")).sendKeys("Applanatest1");
    driver.findElement(By.name("_password")).sendKeys("Student2020!");
    driver.findElement(By.id("_submit")).click();
    new WebDriverWait(driver, 30).until(ExpectedConditions.titleContains("Панель инструментов"));
    driver.findElement(By.xpath("//span[text()='Проекты']")).click();
    driver.findElement(By.xpath("//span[text()='Мои проекты']")).click();
    new WebDriverWait(driver, 30).until(ExpectedConditions.titleContains("Все - Мои проекты - Все проекты - Проекты"));
    driver.findElement(By.xpath("//a[@href='/project/create/' and text()='Создать проект']")).click();
    driver.findElement(By.name("crm_project[name]")).sendKeys("Обучение AQA");
    driver.findElement(By.xpath("//span[text()='Укажите организацию']/following-sibling::span")).click();
    new WebDriverWait(driver, 30);
    driver.findElement(By.xpath("//div[@class='select2-result-label' and text()='123test']")).click();
    driver.findElement(By.xpath("//div[@id='s2id_crm_project_contactMain-uid-613291678a843']")).click();
    new WebDriverWait(driver, 30);
    driver.findElement(By.xpath("//div[@class='select2-result-label' and text()='Brown Bob']")).click();
    driver.findElement(By.name("crm_project[businessUnit]")).click();
    new WebDriverWait(driver, 30);
    driver.findElement(By.xpath("//option[text()='Research & Development']")).click();
    driver.findElement(By.name("crm_project[curator]")).click();
    new WebDriverWait(driver, 30);
    driver.findElement(By.xpath("//select[@name='crm_project[curator]']/option[text()='Ким Юрий']")).click();
    driver.findElement(By.name("crm_project[rp]")).click();
    new WebDriverWait(driver,30);
    driver.findElement(By.xpath("//select[@name='crm_project[rp]']/option[text()='Катков Александр']")).click();
    driver.findElement(By.name("crm_project[administrator]")).click();
    new WebDriverWait(driver, 30);
    driver.findElement(By.xpath("//select[@name='crm_project[administrator]']/option[text()='Исаева Анастасия']")).click();
    driver.findElement(By.name("crm_project[manager]")).click();
    new WebDriverWait(driver, 30);
    driver.findElement(By.xpath("//select[@name='crm_project[manager]']/option[text()='Зайдуллин Рустам']")).click();
    driver.findElement(By.xpath("//button[@class='btn btn-success action-button']")).click();
  }
}
