// Generated by Selenium IDE
package org.example;

import org.junit.jupiter.api.*;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.util.concurrent.TimeUnit;

public class CreateNewUserTest {
    private WebDriver driver;

    @BeforeEach
    public void setUp() {
        System.setProperty("webdriver.chrome.driver", "chromedriver.exe");
        driver = new ChromeDriver();
        driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
    }

    @AfterEach
    public void tearDown() {
        driver.quit();
    }

    @DisplayName("Создание нового пользователя")
    @Test
    public void createNewUser() {
        driver.manage().window().maximize();
        driver.get("https://diary.ru/");
        Assertions.assertNotNull(driver.findElement(By.xpath("//title[text()='Главная страница — @дневники: асоциальная сеть']")), "Нет заголовка окна");
        Assertions.assertEquals("Главная страница — @дневники: асоциальная сеть", driver.getTitle());
        Assertions.assertEquals("Регистрация", driver.findElement(By.xpath("//a[@href='https://diary.ru/user/registration']")).getText());
        driver.findElement(By.xpath("//a[@href='https://diary.ru/user/registration']")).click();
        driver.findElement(By.id("signupform-username")).click();
        driver.findElement(By.id("signupform-username")).sendKeys("sissergey103000998");
        Assertions.assertNotNull(driver.findElement(By.id("signupform-username")), "Поле 'логин' не заполнено");
        Assertions.assertEquals("sissergey103000998", driver.findElement(By.id("signupform-username")).getAttribute("value"));
        driver.findElement(By.id("signupform-password")).click();
        driver.findElement(By.id("signupform-password")).clear();
        Assertions.assertEquals("", driver.findElement(By.id("signupform-password")).getAttribute("value"));
        driver.findElement(By.id("signupform-password")).sendKeys("63623400");
        Assertions.assertNotNull(driver.findElement(By.id("signupform-password")), "Поле 'пароль' не заполнено");
        Assertions.assertEquals("63623400", driver.findElement(By.id("signupform-password")).getAttribute("value"));
        driver.findElement(By.id("signupform-email")).click();
        driver.findElement(By.id("signupform-email")).sendKeys("sissergey@yandex.kcppppp");
        Assertions.assertNotNull(driver.findElement(By.id("signupform-email")), "Поле 'email' не заполнено");
        Assertions.assertEquals("sissergey@yandex.kcppppp", driver.findElement(By.id("signupform-email")).getAttribute("value"));
        Assertions.assertTrue(driver.findElement(By.id("chk_box_user_confirm")).isEnabled());
        driver.findElement(By.id("chk_box_user_confirm")).click();
        Assertions.assertEquals("Зарегистрироваться", driver.findElement(By.id("signup_btn")).getText());
        driver.findElement(By.id("signup_btn")).click();
        new WebDriverWait(driver, 10);
        driver.findElement(By.id("newblogform-title")).click();
        driver.findElement(By.id("newblogform-title")).sendKeys("Мой дневник");
        Assertions.assertNotNull(driver.findElement(By.id("newblogform-title")), "Поле 'название дневника' не заполнено");
        Assertions.assertEquals("Мой дневник", driver.findElement(By.id("newblogform-title")).getAttribute("value"));
        Assertions.assertEquals("Далее", driver.findElement(By.name("new-blogs-button")).getText());
        driver.findElement(By.name("new-blogs-button")).click();
    }
}
