// Generated by Selenium IDE
package org.example;

import org.example.dairy.NewBlogPage;
import org.example.dairy.RegistrationPage;
import org.example.dairy.StartPage;
import org.junit.jupiter.api.*;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.WebDriverWait;


import java.util.concurrent.TimeUnit;

public class CreateNewUserTest {
    private WebDriver driver;

    @BeforeEach
    public void setUp() {
        System.setProperty("webdriver.chrome.driver", "chromedriver.exe");
        driver = new ChromeDriver();
        driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
        driver.manage().window().maximize();
    }

    @AfterEach
    public void tearDown() {
        driver.quit();
    }

    @DisplayName("Создание нового пользователя")
    @Test
    public void createNewUser() {
        driver.get("https://diary.ru/");
        StartPage start = new StartPage(driver);
        Assertions.assertNotNull(start.getTitle(), "Нет заголовка окна");
        Assertions.assertEquals("Главная страница — @дневники: асоциальная сеть", driver.getTitle());
        Assertions.assertEquals("Регистрация", start.getReg().getText());
        start.reg();
        RegistrationPage page = new RegistrationPage(driver)
                .username("sissergey103000998")
                .password("63623400")
                .email("sissergey@yandex.kcppppp")
                .checkBox();
        Assertions.assertTrue(page.getCheckBox().isEnabled());
        Assertions.assertNotNull(page.getUsername(), "Поле 'логин' не заполнено");
        Assertions.assertEquals("sissergey103000998", page.getUsername().getAttribute("value"));
        Assertions.assertNotNull(page.getPassword(), "Поле 'пароль' не заполнено");
        Assertions.assertEquals("63623400", page.getPassword().getAttribute("value"));
        Assertions.assertNotNull(page.getEmail(), "Поле 'email' не заполнено");
        Assertions.assertEquals("sissergey@yandex.kcppppp", page.getEmail().getAttribute("value"));
        Assertions.assertEquals("Зарегистрироваться", page.getSignUpBtn().getText());
        page.signUpBtn();
        new WebDriverWait(driver, 10);
        NewBlogPage page1 = new NewBlogPage(driver)
                .title("Мой дневник");
        Assertions.assertNotNull(page1.getTitle(), "Поле 'название дневника' не заполнено");
        Assertions.assertEquals("Мой дневник", page1.getTitle().getAttribute("value"));
        Assertions.assertEquals("Далее", page1.getBtn().getText());
        page1.btn();
    }
}
